[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "python3 -m pip install --user pymupdf google-generativeai pillow"
]

[phases.build]
cmds = [
    "php artisan storage:link || true",
    "npm install",
    "npm run build"
]

[start]
cmd = "php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan serve --host=0.0.0.0 --port=$PORT"
